spring:
  cloud:
    consul:
      host: consul-consul-server
      port: 8500
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 20s
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}
  application:
    name: ProductService
