apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-www
  labels:
    app: backend-www
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-www
  template:
    metadata:
      labels:
        app: backend-www
    spec:
      containers:
      - name: backend-www
        image: ideal/backend-www:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-www
  labels:
    app: backend-www
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: backend-www
