apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
      - name: backend-service
        image: ideal/backend-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: CONSUL_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP

